<h2 style=color:red>Basic image manipulations 1<h2>

In [2]:
import numpy as np
from PIL import Image as im
 
red=np.full((512,512),255,dtype='uint8')
green=np.full((512,512),0,dtype='uint8')
blue=np.full((512,512),0,dtype='uint8')
# stacking three channels 
arr=np.stack((red,green,blue),axis=-1)
# converting an image into array
img=im.fromarray(arr)
img.show()
print(red)
i=im.open(r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg')
i.show()
# converting an image into array
img=np.array(i)
print(img)
print(i.size)
# adding a alpha channel to make the picture blur
opc=np.full((img.shape[0], img.shape[1]),100,dtype='uint8') 
 #need to use img.shape[0]This ensures opc matches the height and width of the loaded image.
st_arr=np.stack((img[:,:,0],img[:,:,1],img[:,:,2],opc),axis=-1)
st_img=im.fromarray(st_arr,mode='RGBA') #When creating the new image from the array, use RGBA mode since you’re adding an alpha channel.
st_img.show()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[[ 90  14  18]
  [ 90  14  18]
  [ 92  12  15]
  ...
  [ 22   3   5]
  [ 24   4   6]
  [ 24   4   6]]

 [[ 88  12  16]
  [ 88  12  16]
  [ 90  10  13]
  ...
  [ 17   0   0]
  [ 18   0   0]
  [ 19   0   1]]

 [[ 86  10  12]
  [ 87  11  13]
  [ 89   9  12]
  ...
  [ 16   0   0]
  [ 18   0   1]
  [ 18   0   1]]

 ...

 [[138  30  53]
  [137  29  52]
  [140  32  55]
  ...
  [246 173 202]
  [248 175 204]
  [249 176 205]]

 [[139  31  54]
  [138  30  53]
  [139  31  54]
  ...
  [244 169 199]
  [246 171 201]
  [247 172 202]]

 [[140  32  55]
  [138  30  53]
  [139  31  54]
  ...
  [242 167 197]
  [243 168 198]
  [244 169 199]]]
(2268, 4032)


<h1>Grey Scale<h1>

In [3]:
import numpy as np
from PIL import Image as im
i=im.open(r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg')
# i.show()
i = i.convert('RGB')
red_channel, green_channel, blue_channel = i.split() #image.split() separates the Red, Green, and Blue channels into individual grayscale images.

# Display each channel
#show() opens each channel in a separate window using the default image viewer on your system.
red_channel.show(title="Red Channel")
green_channel.show(title="Green Channel")
blue_channel.show(title="Blue Channel")
image_array = np.array(i)

# Compute the average of the RGB channels
grayscale_array = image_array.mean(axis=2).astype(np.uint8)

# Convert the grayscale array back to an image
grayscale_image = im.fromarray(grayscale_array)

# Display the grayscale image
grayscale_image.show(title="Grayscale Image")

<h1 style=color=red>Blending Image<h1>

In [11]:
import numpy as np
from PIL import Image as im
i=im.open(r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg')
# i.show()
i2=im.open(r'C:\Users\AZRA QADIR\Desktop\pexels-pixabay-47367.jpg')
# i2.show()
i=np.resize(i,(2268,4032))
i2=np.resize(i2,(2268,4032))
print(i.size)
print(i2.size)
img=np.array(i)
img2=np.array(i2)
blended_img=0.5*img+0.8*img2
print(blended_img)
blended_img=im.fromarray(blended_img)
blended_img.show()

9144576
9144576
[[ 45.    7.    9.  ...  49.5  14.5  15.5]
 [ 49.   13.5  15.5 ...  59.5   2.5  19.5]
 [ 63.5   4.   24.  ...  28.5   1.    3.5]
 ...
 [266.6 208.1 234.6 ... 151.   89.   94.5]
 [151.   89.   94.5 ...  72.    9.   14.5]
 [ 70.    7.   12.5 ... 212.3 172.3 178.8]]


In [13]:
from PIL import Image
import numpy as np

base_image_path = (r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg' )
watermark_image_path = (r'C:\Users\AZRA QADIR\Desktop\pexels-pixabay-47367.jpg')

watermark_opacity = 0.5  

base_img = Image.open(base_image_path).convert('RGB')
watermark_img = Image.open(watermark_image_path).convert('RGBA')

x = 0
y = 0

blended_img = Image.new('RGB', base_img.size) 

blended_img.paste(base_img, (0, 0)) 

blended_img.paste(watermark_img, (x, y), mask=watermark_img.split()[3]) 

blended_img.save('watermarked_image.jpg')
print(watermark_img)
watermark_img.show()
blended_img.show()

<PIL.Image.Image image mode=RGBA size=2237x2153 at 0x18799E9C870>


<h1>Art<h1>

In [14]:
from PIL import Image
import numpy as np

base_image_path = r'c:\Users\AZRA QADIR\Desktop\—Pngtree—red long-haired santa hat_5671492.png' 
texture_image_path = r'C:\Users\AZRA QADIR\Desktop\pexels-pixabay-47367.jpg' 
texture_scale = 0.5 
texture_blend_ratio = 0.3

base_img = Image.open(base_image_path).convert('RGB')
texture_img = Image.open(texture_image_path).convert('RGB')

texture_img = texture_img.resize((int(base_img.width * texture_scale), 
                                     int(base_img.height * texture_scale)))

if base_img.size != texture_img.size:
  base_img = base_img.resize(texture_img.size)

base_img_array = np.array(base_img)
texture_img_array = np.array(texture_img)

blended_array = (texture_blend_ratio * texture_img_array) + \
                   ((1 - texture_blend_ratio) * base_img_array)
blended_array = np.clip(blended_array, 0, 255).astype(np.uint8)

stylized_image = Image.fromarray(blended_array)
stylized_image.save('stylized_landscape.jpg')   
stylized_image.show()

<h1>Augumentation<h1>

In [15]:
from PIL import Image
import numpy as np
import random

image1_path = r'C:\Users\AZRA QADIR\Desktop\pexels-pixabay-47367.jpg' 
image2_path = r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg'
num_blends = 10

img1 = Image.open(image1_path).convert('RGB')
img2 = Image.open(image2_path).convert('RGB')

img1 = img1.resize(img2.size) 
img2 = img2.resize(img1.size) 

img1_array = np.array(img1)
img2_array = np.array(img2)

for i in range(num_blends):
  alpha = random.random()
  blended_array = alpha * img1_array + (1 - alpha) * img2_array
  blended_array = np.clip(blended_array, 0, 255).astype(np.uint8)
  blended_image = Image.fromarray(blended_array)
  blended_image.save(f"blended_image_{i+1}.jpg")
  blended_image.show()

<h1>Brightness</h1>

In [16]:

from PIL import Image
import numpy as np

image_path = r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg' 
brightness_value = 30  

img = Image.open(image_path).convert('RGB')
img_array = np.array(img)

adjusted_array = img_array + brightness_value
adjusted_array = np.clip(adjusted_array, 0, 255).astype(np.uint8)

adjusted_img = Image.fromarray(adjusted_array)
adjusted_img.save('brighter_image.jpg') 
adjusted_img.show()

img = Image.open(image_path).convert('RGB')
img_array = np.array(img)

adjusted_array = img_array - 50 
adjusted_array = np.clip(adjusted_array, 0, 255).astype(np.uint8)

adjusted_img = Image.fromarray(adjusted_array)
adjusted_img.save('darker_image.jpg')
adjusted_img.show()

<h1>Overlying a small image<h1>

In [17]:
from PIL import Image
import numpy as np

# File paths (ensure these are correct)
base_image_path = r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg'
overlay_image_path = r'C:\Users\AZRA QADIR\Desktop\—Pngtree—red long-haired santa hat_5671492.png'

# Offset for the overlay position
x_offset = 50
y_offset = 50

# Open base image and overlay image
try:
    base_img = Image.open(base_image_path).convert('RGBA')
    overlay_img = Image.open(overlay_image_path).convert('RGBA')
except Exception as e:
    print(f"Error opening images: {e}")
    exit()

# Resize overlay image if it's larger than the base image
if overlay_img.size[0] > base_img.size[0] or overlay_img.size[1] > base_img.size[1]:
    overlay_img = overlay_img.resize(base_img.size, Image.Resampling.LANCZOS)

# Convert images to numpy arrays
base_img_array = np.array(base_img)
overlay_img_array = np.array(overlay_img)

# Calculate overlay region
x1 = max(x_offset, 0)
y1 = max(y_offset, 0)
x2 = min(x_offset + overlay_img.size[0], base_img.size[0])
y2 = min(y_offset + overlay_img.size[1], base_img.size[1])

# Crop the overlay to fit within the base image dimensions
overlay_cropped = overlay_img_array[:y2-y1, :x2-x1, :]

# Extract alpha mask from the overlay
overlay_mask = overlay_cropped[:, :, 3] / 255.0  # Normalize alpha channel to range [0, 1]
overlay_mask = np.expand_dims(overlay_mask, axis=2)  # Add an extra dimension for broadcasting

# Blend the overlay with the base image using the alpha mask
base_img_array[y1:y2, x1:x2, :3] = (1 - overlay_mask) * base_img_array[y1:y2, x1:x2, :3] + \
                                   (overlay_mask * overlay_cropped[:, :, :3])

# Convert blended array back to image
combined_img = Image.fromarray(base_img_array.astype(np.uint8), 'RGBA')

# Save and show combined image
combined_img.save('combined_image.png')  # Save as PNG to preserve transparency
combined_img.show()

<h1>Tiling<h1>

In [18]:
from PIL import Image


image_path = r'C:\Users\AZRA QADIR\Desktop\pexels-beevee-1020478.jpg' 
image = Image.open(image_path)


width, height = image.size


half_width = width // 2
half_height = height // 2


part1 = image.crop((0, 0, half_width, half_height))  # Top-left
part2 = image.crop((half_width, 0, width, half_height))  # Top-right
part3 = image.crop((0, half_height, half_width, height))  # Bottom-left
part4 = image.crop((half_width, half_height, width, height))  # Bottom-right

# Save each part as a separate file
part1.save("part1.jpg")
part2.save("part2.jpg")
part3.save("part3.jpg")
part4.save("part4.jpg")

# Rearrange the tiles in a different order (e.g., swap top-left with bottom-right, etc.)
new_order = [part4, part2, part3, part1]

# Create a new blank image for stitching
stitched_image = Image.new("RGB", (width, height))

# Paste the parts in the new order
stitched_image.paste(new_order[0], (0, 0))  # Top-left
stitched_image.paste(new_order[1], (half_width, 0))  # Top-right
stitched_image.paste(new_order[2], (0, half_height))  # Bottom-left
stitched_image.paste(new_order[3], (half_width, half_height))  # Botom-right

# Save and show the stitched image
stitched_image.save("stitched_image.jpg")
stitched_image.show()

<h1>Noise Addition<h1>

In [19]:
from PIL import Image
import numpy as np

# Load the image
image_path = r'C:\Users\AZRA QADIR\Desktop\pexels-pixabay-47367.jpg'  
image = Image.open(image_path).convert('RGB')

# Convert image to numpy array
image_array = np.array(image)

# Add random noise to the image array
noise = np.random.randint(0, 50, image_array.shape, dtype='uint8')
noisy_image_array = image_array + noise

# Clip the values to ensure they remain valid (0-255)
noisy_image_array = np.clip(noisy_image_array, 0, 255)

# Convert back to an image
noisy_image = Image.fromarray(noisy_image_array.astype('uint8'))

# Save the noisy image
noisy_image.save("noisy_image.jpg")
noisy_image.show()

<h1>Flipping <h1>

In [20]:
from PIL import Image
import numpy as np

# Load the image
image_path = r'C:\Users\AZRA QADIR\Desktop\pexels-pixabay-47367.jpg'  # Replace with your image file
image = Image.open(image_path).convert('RGB')

# Perform horizontal flip
horizontally_flipped_image = image.transpose(Image.FLIP_LEFT_RIGHT)
horizontally_flipped_image.save("horizontally_flipped_image.jpg")
horizontally_flipped_image.show()

# Perform vertical flip
vertically_flipped_image = image.transpose(Image.FLIP_TOP_BOTTOM)
vertically_flipped_image.save("vertically_flipped_image.jpg")
vertically_flipped_image.show()

# Perform rotation (90 degrees clockwise)
rotated_image_90 = image.rotate(-90, expand=True)
rotated_image_90.save("rotated_image_90.jpg")
rotated_image_90.show()

# Perform rotation (180 degrees)
rotated_image_180 = image.rotate(180, expand=True)
rotated_image_180.save("rotated_image_180.jpg")
rotated_image_180.show()

# Perform rotation (270 degrees clockwise)
rotated_image_270 = image.rotate(-270, expand=True)
rotated_image_270.save("rotated_image_270.jpg")
rotated_image_270.show()